### ISSUE TITLE
[Feat] Avatar, ProfileAvatar 컴포넌트 구현 

### ISSUE THREAD

**Issue by seovee** [coding-union-kr/siltarae-fe#6]
# 이슈설명
Avartar(프로필) 컴포넌트 구현하기

# 체크리스트

- [x]  box-shadow 추가하기

# 참고자료 
<img width="363" alt="스크린샷 2023-12-08 오후 2 39 19" src="https://github.com/coding-union-kr/siltarae-fe/assets/18073169/409e1999-2aca-432e-9956-8f86ef640826">

**Comment by cottonpup** [comment]
- Avatar
- ProfileAvatar 
로 분리
