### ISSUE TITLE
[Suggestion] VScode 내 주석 작성

### ISSUE THREAD

**Issue by cottonpup** [coding-union-kr/siltarae-fe#62]
# 제안
- `NOTE`, `FIXME`, `TODO`, `[R]` 검색하시면 바로 볼 수 있게 작성해두겠습니다! 시간이 될 때마다 이슈에다가도 적고 개인적인 참고용으로도 작성할게요! 필요없는 주석은 바로바로 삭제하겠습니다.

- `NOTE`: 참고사항
- `FIXME`: 고쳐야하는 사항
- `TODO`: 해야할 것
- `[R]`: 현재 리팩토링중인 것

  
# 참고자료 

![Screenshot 2023-12-22 at 14 22 08](https://github.com/coding-union-kr/siltarae-fe/assets/67526014/29b3c76c-b566-4a2c-ab52-0993f3cabf47)

**Comment by seovee** [comment]
오호 좋아요 좋아요. 좋은 방법 배웁니다!
