### ISSUE TITLE
[Bug] 한국어로 태그 추가시 태그가 두 개 올라가는 이슈

### ISSUE THREAD

**Issue by cottonpup** [coding-union-kr/siltarae-fe#96]
# 버그내용
- 한국어로 태그 추가시 태그가 두 개 올라가는 이슈
   - Network 확인 시, 두 번 요청이 보내지는데 디버깅을 해봐야할 거 같다.
- 영어로 태그 추가시는 태그가 정상적으로 한개만 올라간다

## 버그발생 페이지 & 링크
RegisterPostModal

**Comment by seovee** [comment]
## 중복 클릭되는 원인은 "한글은 조합문자"이기 때문!
- 브라우저가 글자가 조합중인지 끝난 상태인지 알 수 없기 때문에 두번 호출되는 오류가 발생

_*구글링해보니 chrome브라우저 사용 시 keydown을 console로 찍어보면 이벤트가 두번 발생_

## 해결방법
- 그래서 이벤트 속성 중 isComposing속성을 사용
- 한글을 입력하는 동안에는 `true`, 엔터를 치면 `false`가 찍혀 에러를 해결할 수 있음
`if(e.key === "Enter" && !e.nativeEvent.isComposing)`
